services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - postgres-net

  backup:
    build: .
    environment:
      # PostgreSQL connection
      PG_HOST: postgres
      PG_PORT: 5432
      PG_USER: postgres
      PG_DATABASE: postgres
      PG_PASSWORD: postgres

      # Cloudflare R2 configuration
      RCLONE_CONFIG_REMOTE_TYPE: s3
      RCLONE_CONFIG_REMOTE_PROVIDER: Minio
      RCLONE_CONFIG_REMOTE_ENDPOINT: "http://minio:9000"
      RCLONE_CONFIG_REMOTE_ACCESS_KEY_ID: test
      RCLONE_CONFIG_REMOTE_SECRET_ACCESS_KEY: test

      # Backup configuration
      RCLONE_PATH: "${BACKUP_PATH:-backups}"
      BACKUP_SCHEDULE: "${BACKUP_SCHEDULE:-0 1 * * *}"

    entrypoint: ["/bin/sh", "-c"]
    command: |
      echo "$${BACKUP_SCHEDULE} /usr/local/bin/backup.sh" > /var/spool/cron/crontabs/root && \
      crond -f -d 8

    depends_on:
      postgres:
        condition: service_healthy

    networks:
      - postgres-net

  minio:
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: test
      MINIO_ROOT_PASSWORD: test
    command: server /data
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - postgres-net
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  postgres-net:
    name: postgres-net
